# -*- coding: utf-8 -*-
"""Phishtank-data-NLP_Agent_FineTuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERGgAp7xISXRChDsGDle_xQ07z4D1WLy

# 🔐 NLP Analysis Agent — Fine-Tuning Notebook
### Hybrid Multi-Agent Phishing Detection Framework

This notebook fine-tunes:
- **Model 1**: TF-IDF + Logistic Regression (fast baseline)
- **Model 2**: DistilBERT (primary high-accuracy model)

**Dataset columns expected**: `text_combined`, `label` (0=safe, 1=phishing)

---
### Steps:
1. Mount Google Drive
2. Upload your CSV files
3. Run all cells top to bottom
4. Models auto-save to Google Drive
5. Download models to your local project

```
# This is formatted as code
```

##  Step 1 — Mount Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

import os
# Create project folders in Drive
os.makedirs('/content/drive/MyDrive/phishing_project-v2/data', exist_ok=True)
os.makedirs('/content/drive/MyDrive/phishing_project-v2/models', exist_ok=True)

print('✅ Google Drive mounted!')
print('📁 Upload your CSV files to: /content/drive/MyDrive/phishing_project-v2/data/')

"""## ✅ Step 2 — Install Dependencies"""

!pip install transformers datasets scikit-learn pandas numpy torch -q
print('✅ All dependencies installed!')

"""## ✅ Step 3 — Load & Combine All Datasets"""

import pandas as pd
import numpy as np
import os

# Update this path to where your CSV is located in Colab
DATA_PATH = '/content/drive/MyDrive/phishing_project-v2/data/nlp_finetune_dataset.csv'

print(f"Loading custom DOM dataset...")
combined = pd.read_csv(DATA_PATH)

# Map string labels to integers (1 = Phishing, 0 = Safe)
# This ensures it works perfectly with your downstream training code
if combined['label'].dtype == object:
    combined['label'] = combined['label'].map({'phishing': 1, 'legitimate': 0})

# Drop any accidental empty rows and shuffle
combined = combined.dropna()
combined = combined.sample(frac=1, random_state=42).reset_index(drop=True)

print(f'\n📊 COMBINED DATASET')
print(f'   Total samples : {len(combined)}')
print(f'   Phishing (1)  : {combined["label"].sum()}')
print(f'   Safe (0)      : {(combined["label"]==0).sum()}')
print(f'   Balance ratio : {combined["label"].mean():.2%} phishing')

"""## ✅ Step 4 — Data Cleaning & Balancing"""

from sklearn.utils import resample

# 1. Basic safety checks (converting to string and stripping spaces)
combined['text'] = combined['text'].astype(str)
combined['text'] = combined['text'].str.strip()

# Change the limit to > 2 so we don't accidentally delete short UI buttons like "Login"
combined = combined[combined['text'].str.len() > 2]

# 2. Balance dataset (Just a safety net! Your scraper already balanced it)
phishing_df = combined[combined['label'] == 1]
safe_df = combined[combined['label'] == 0]

n_samples = min(len(phishing_df), len(safe_df))

phishing_balanced = resample(phishing_df, n_samples=n_samples, random_state=42)
safe_balanced = resample(safe_df, n_samples=n_samples, random_state=42)

# 3. Final merge and shuffle
balanced = pd.concat([phishing_balanced, safe_balanced])
balanced = balanced.sample(frac=1, random_state=42).reset_index(drop=True)

texts = balanced['text'].tolist()
labels = balanced['label'].tolist()

print(f'✅ Balanced web dataset ready')
print(f'   Total : {len(balanced)}')
print(f'   Phishing : {sum(labels)}')
print(f'   Safe     : {len(labels) - sum(labels)}')

"""## ✅ Step 5 — Train Model 1: TF-IDF + Logistic Regression"""

import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import os

MODEL_DIR = '/content/drive/MyDrive/phishing_project-v2/models'

print('🔄 Training TF-IDF + Logistic Regression...')

X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.2, random_state=42, stratify=labels
)

# TF-IDF Vectorizer
vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    max_features=15000,
    sublinear_tf=True,
    min_df=2
)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Logistic Regression
lr_model = LogisticRegression(C=1.0, max_iter=1000, random_state=42)
lr_model.fit(X_train_vec, y_train)

# Evaluate
y_pred = lr_model.predict(X_test_vec)
acc = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f'\n📊 TF-IDF + LR Results:')
print(f'   Accuracy : {acc:.4f} ({acc*100:.2f}%)')
print(f'   F1 Score : {f1:.4f}')
print(f'\n{classification_report(y_test, y_pred, target_names=["Safe", "Phishing"])}')

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Safe', 'Phishing'],
            yticklabels=['Safe', 'Phishing'])
plt.title('TF-IDF + LR Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.tight_layout()
os.makedirs(MODEL_DIR, exist_ok=True) # Ensure directory exists
plt.savefig(f'{MODEL_DIR}/tfidf_confusion_matrix.png')
plt.show()

# Save models
with open(f'{MODEL_DIR}/tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)
with open(f'{MODEL_DIR}/tfidf_model.pkl', 'wb') as f:
    pickle.dump(lr_model, f)

print(f'\n✅ TF-IDF model saved to Google Drive!')

"""## ✅ Step 6 — Train Model 2: DistilBERT Fine-Tuning"""

import torch
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)
from torch.utils.data import Dataset
from sklearn.model_selection import train_test_split

# Check GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'🖥️  Device: {device}')
if device == 'cuda':
    print(f'   GPU: {torch.cuda.get_device_name(0)}')
else:
    print('⚠️  No GPU found! Go to Runtime > Change runtime type > T4 GPU')

# Dataset class
class PhishingDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    def __len__(self):
        return len(self.labels)
    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.2, random_state=42, stratify=labels
)

# Tokenize — truncate to 128 tokens for speed (phishing texts are usually short)
print('\n🔄 Loading DistilBERT tokenizer...')
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

train_enc = tokenizer(X_train, truncation=True, padding=True, max_length=512)
test_enc  = tokenizer(X_test,  truncation=True, padding=True, max_length=512)

train_dataset = PhishingDataset(train_enc, y_train)
test_dataset  = PhishingDataset(test_enc,  y_test)

print(f'✅ Tokenization done')
print(f'   Train samples : {len(train_dataset)}')
print(f'   Test samples  : {len(test_dataset)}')

from sklearn.metrics import accuracy_score, f1_score

BERT_MODEL_PATH = f'{MODEL_DIR}/distilbert_phishing'

# Load model
print('🔄 Loading DistilBERT model...')
model = DistilBertForSequenceClassification.from_pretrained(
    'distilbert-base-uncased',
    num_labels=2
)

# Metrics function
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = logits.argmax(axis=-1)
    return {
        'accuracy': accuracy_score(labels, preds),
        'f1': f1_score(labels, preds)
    }

# Updated Training arguments
training_args = TrainingArguments(
    output_dir=BERT_MODEL_PATH,
    num_train_epochs=3,
    per_device_train_batch_size=16, # Lowered to prevent CUDA Out of Memory
    per_device_eval_batch_size=16,  # Lowered to prevent CUDA Out of Memory
    warmup_steps=10,                # Adjusted for a 600-row dataset
    weight_decay=0.01,
    eval_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    metric_for_best_model='f1',
    logging_dir=f'{MODEL_DIR}/logs',
    logging_steps=10,               # Lowered so you can see the updates!
    fp16=True if device == 'cuda' else False,
    report_to='none'
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

print('🚀 Starting DistilBERT fine-tuning...')
print('   Expected time: ~8-12 mins on T4 GPU')
print('   Watch the loss decrease each epoch!\n')
trainer.train()

"""## ✅ Step 7 — Evaluate DistilBERT"""

from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

print('📊 Evaluating DistilBERT on test set...')
predictions = trainer.predict(test_dataset)
y_pred_bert = predictions.predictions.argmax(axis=-1)

acc_bert = accuracy_score(y_test, y_pred_bert)
f1_bert  = f1_score(y_test, y_pred_bert)

print(f'\n📊 DistilBERT Results:')
print(f'   Accuracy : {acc_bert:.4f} ({acc_bert*100:.2f}%)')
print(f'   F1 Score : {f1_bert:.4f}')
print(f'\n{classification_report(y_test, y_pred_bert, target_names=["Safe", "Phishing"])}')

# Confusion Matrix
cm_bert = confusion_matrix(y_test, y_pred_bert)
plt.figure(figsize=(6,4))
sns.heatmap(cm_bert, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Safe', 'Phishing'],
            yticklabels=['Safe', 'Phishing'])
plt.title('DistilBERT Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.tight_layout()
plt.savefig(f'{MODEL_DIR}/distilbert_confusion_matrix.png')
plt.show()

# Comparison
print('\n' + '='*45)
print('  MODEL COMPARISON')
print('='*45)
print(f'  TF-IDF + LR  →  Accuracy: {acc*100:.2f}%  F1: {f1:.4f}')
print(f'  DistilBERT   →  Accuracy: {acc_bert*100:.2f}%  F1: {f1_bert:.4f}')
print('='*45)

"""## ✅ Step 8 — Save Everything to Google Drive"""

# Save DistilBERT model + tokenizer
trainer.save_model(BERT_MODEL_PATH)
tokenizer.save_pretrained(BERT_MODEL_PATH)

# Save results summary
results_summary = f"""NLP Agent Fine-Tuning Results
==============================
Dataset: Phishing Email (Kaggle)
Total samples used: {len(balanced)}
Train / Test split: 80% / 20%

TF-IDF + Logistic Regression:
  Accuracy : {acc*100:.2f}%
  F1 Score : {f1:.4f}

DistilBERT (fine-tuned):
  Accuracy : {acc_bert*100:.2f}%
  F1 Score : {f1_bert:.4f}
"""

with open(f'{MODEL_DIR}/results_summary.txt', 'w') as f:
    f.write(results_summary)

print('✅ All models saved to Google Drive!')
print(f'\n📁 Your files are at:')
print(f'   {MODEL_DIR}/tfidf_model.pkl')
print(f'   {MODEL_DIR}/tfidf_vectorizer.pkl')
print(f'   {MODEL_DIR}/distilbert_phishing/')
print(f'   {MODEL_DIR}/results_summary.txt')
print(f'   {MODEL_DIR}/tfidf_confusion_matrix.png')
print(f'   {MODEL_DIR}/distilbert_confusion_matrix.png')

print(results_summary)